site_name: FPACAF
use_directory_urls: false

copyright: Copyright &copy; 2022 Fernando Ferraz Ribeiro

theme:
  features:
    #- navigation.sections
    - toc.integrate
    #- navigation.tabs
  name: material   
  language: en-custom
  custom_dir: docs/overrides
  # favicon: figs/chart_white/icons8-doughnut-chart-96.png
  # logo: figs/chart_white/icons8-doughnut-chart-96.png


  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

site_url: "https://255ribeiro.github.io/fpacaf/"
repo_url: "https://github.com/255ribeiro/fpacaf"
repo_name: "255ribeiro/fpacaf" 

nav:
  - Home: index.md

  - Introdução: ./topics/01_Intro_fpacaf/intro.md
  - Fluxogramas: ./topics/01A_fluxogramas/fluxogramas.md

  - Intro Python:
    - Operadores: ./topics/02_intro_python/escadas.md
    - Decisões lógicas: ./topics/03_intro_python/if_else.md
    - Loops: ./topics/04_intro_loops/loops.md
    - Funções : ./topics/04a_func_python/functionsPyton3.md
  - Intro Rhino Python:  ./topics/05_intro_rhino_py/rhino_python.md
  - Intro Grasshopper: ./topics/06_intro_grasshopper/intro_grasshopper.md
  - Treliças: ./topics/07_trelicas/trelicas.md
  - Malhas:
    - Malha regular: ./topics/08_malha_reg/malha_reg.md
    - Malha Irregular: ./topics/09_malha_irreg/malha_irreg.md
  - Multiplos pavimentos: ./topics/10_multi_pav/multipav.md
  - Listas e árvores de dados: ./topics/12_lists_data_tree/lists_and_data_trees.md
  - Fractais: ./topics/13_fractals/fractais.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - toc:
      toc_depth: 1

extra_css:
  - overrides/css/extra_css.css

plugins:
  - mkdocs-jupyter:
      kernel_name:
      include: ["*.py", "*.ipynb"]
      include_source: True
      # ignore: ["./flask/hello_flask.ipynb"]
      execute: False
      # execute_ignore: ["./flask_dash/*/*"]

      


extra:
  social:
      - icon: fontawesome/brands/github
        link: https://github.com/255ribeiro
      - icon: fontawesome/brands/youtube
        link: https://www.youtube.com/channel/UCCkMaRdD7PBWhs4JgH5s6_w
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/in/fernando-ferraz-ribeiro-b49a7bb0/
      - icon: fontawesome/solid/envelope
        link: mailto:ffribeiro@gmail.com
